### ISSUE TITLE
Request : verbose mode 

### ISSUE THREAD

**Issue by ehsandeep** [gwen001/ultimate-open-redirect#1]
it will be good if user have option to see verbose mode while testing payloads to make sure everything going in flow .

**Comment by gwen001** [comment]
Hum yes, I didn't work to much on this script. A message is displayed every 1500 tests:

```
Current 0...
Current 1500...
Current 3000...
```

You can change the variable `$cnt_notice` that handles this value. A specific message is also displayed when an open redirect is found.

Thank you anyway for your commitment.

**Comment by ehsandeep** [comment]
thanks , i will play with $cnt_notice for myself, anyway just fyi while running this script i come to know it won't stop if we want to stop it in between CLT+C or CLT+Z, console shows it's got stop after some second it keep continue with displaying Current 1500... or what any count it reach at that time, so ultimately it won't get cancel untill it finished.

**Comment by gwen001** [comment]
Yes you're right, because `launch.sh` calls `test_open_redirect.php` as a child process.
